#!/bin/bash

echo "*********************************************************"
echo "Running git pre-commit hook. Running Spotless Apply... "
echo "*********************************************************"

../gradlew ktlintCheck

ktlintCheckStatus=$?

if [[ $ktlintCheckStatus -ne 0 ]]; then
  exit 1
else
  exit 0
fi
